# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ynTPdkNsRRmUHjw2RPyDtmmdz06oVnap
"""

Health = 0
Lives = 0

if Health <= 0:
  Alive = False
else:
  Alive = True

if Alive == True:
  print("The Journey Continues")
else:
  print("Game Over")